/**
 *
 * This file reperesents mock data for display testing functionality.
 * It is to be replaced and deleted once the backend is implemented
 */
import { DeliveryStatusTypes, type Provider, type WebHookEvent } from './types';

export const MOCK_DATA: WebHookEvent[] = (
    [
        {
            id: 'evt_01j9k2m3n4p5q6r7s8t9u0v1',
            provider_id: 'pvdr_001',
            provider: 'stripe',
            event_id: 'evt_1OwXyZ2eZvKYlo2C1nBkQ9Ab',
            event_type: 'payment_intent.succeeded',
            received_at: '2026-03-25T14:32:01Z',
            created_at: '2026-03-25T14:32:01Z',
            delivery_status: DeliveryStatusTypes.Delivered,
            response_code: 200,
            retry_count: 0,
            next_retry_at: null,
            forwarded_to: 'https://api.myapp.com/webhooks/stripe',
            last_error: null,
            headers: {
                'stripe-signature': 't=1711378321,v1=abc123...',
                'content-type': 'application/json',
                'user-agent': 'Stripe/1.0 (+https://stripe.com/docs/webhooks)',
            },
            payload: {
                id: 'pi_3OwXyZ2eZvKYlo2C1nBkQ9Ab',
                object: 'payment_intent',
                amount: 4999,
                currency: 'usd',
                status: 'succeeded',
                customer: 'cus_PqRsT1234567',
            },
        },
        {
            id: 'evt_02j9k2m3n4p5q6r7s8t9u0v2',
            provider_id: 'pvdr_002',
            provider: 'github',
            event_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
            event_type: 'push',
            received_at: '2026-03-25T14:28:44Z',
            created_at: '2026-03-25T14:28:44Z',
            delivery_status: DeliveryStatusTypes.Failed,
            response_code: 502,
            retry_count: 3,
            next_retry_at: null,
            forwarded_to: 'https://api.myapp.com/webhooks/github',
            last_error: '502 Bad Gateway — upstream connection refused',
            headers: {
                'x-github-event': 'push',
                'x-hub-signature-256': 'sha256=def456...',
                'content-type': 'application/json',
            },
            payload: {
                ref: 'refs/heads/main',
                repository: { full_name: 'acme/backend', private: false },
                pusher: { name: 'jdoe', email: 'jdoe@acme.com' },
                commits: [{ id: 'a1b2c3d', message: 'fix: retry backoff logic' }],
            },
        },
        {
            id: 'evt_03j9k2m3n4p5q6r7s8t9u0v3',
            provider_id: 'pvdr_001',
            provider: 'stripe',
            event_id: 'evt_1Ow9Zx2eZvKYlo2CmNpQrStU',
            event_type: 'customer.subscription.updated',
            received_at: '2026-03-25T14:21:09Z',
            created_at: '2026-03-25T14:21:09Z',
            delivery_status: DeliveryStatusTypes.Retrying,
            response_code: 503,
            retry_count: 1,
            next_retry_at: '2026-03-25T14:36:09Z',
            forwarded_to: 'https://api.myapp.com/webhooks/stripe',
            last_error: '503 Service Unavailable — destination timeout',
            headers: {
                'stripe-signature': 't=1711377669,v1=ghi789...',
                'content-type': 'application/json',
            },
            payload: {
                id: 'sub_1Ow9Zx2eZvKYlo2CmNpQrStU',
                object: 'subscription',
                status: 'active',
                plan: { id: 'plan_pro_monthly', amount: 2900 },
            },
        },
        {
            id: 'evt_04j9k2m3n4p5q6r7s8t9u0v4',
            provider_id: 'pvdr_003',
            provider: 'sns',
            event_id: '22b80b92-fdea-4c2c-8f9d-bdfb0c7bf324',
            event_type: 'Notification',
            received_at: '2026-03-25T14:18:33Z',
            created_at: '2026-03-25T14:18:33Z',
            delivery_status: DeliveryStatusTypes.Delivered,
            response_code: 200,
            retry_count: 0,
            next_retry_at: null,
            forwarded_to: 'https://api.myapp.com/webhooks/sns',
            last_error: null,
            headers: {
                'x-amz-sns-message-type': 'Notification',
                'x-amz-sns-topic-arn': 'arn:aws:sns:us-east-1:123456789012:MyTopic',
            },
            payload: {
                Type: 'Notification',
                MessageId: '22b80b92-fdea-4c2c-8f9d-bdfb0c7bf324',
                TopicArn: 'arn:aws:sns:us-east-1:123456789012:MyTopic',
                Subject: 'deploy-complete',
                Message: '{"env":"production","service":"api","version":"1.4.2"}',
            },
        },
        {
            id: 'evt_05j9k2m3n4p5q6r7s8t9u0v5',
            provider_id: 'pvdr_001',
            provider: 'stripe',
            event_id: 'evt_1Ow8Wx2eZvKYlo2CpQrSt3Uv',
            event_type: 'invoice.payment_failed',
            received_at: '2026-03-25T14:17:55Z',
            created_at: '2026-03-25T14:17:55Z',
            delivery_status: DeliveryStatusTypes.Queued,
            response_code: null,
            retry_count: 0,
            next_retry_at: null,
            forwarded_to: 'https://api.myapp.com/webhooks/stripe',
            last_error: null,
            headers: {
                'stripe-signature': 't=1711377475,v1=jkl012...',
                'content-type': 'application/json',
            },
            payload: {
                id: 'in_1Ow8Wx2eZvKYlo2CpQrSt3Uv',
                object: 'invoice',
                amount_due: 9900,
                currency: 'usd',
                customer: 'cus_AbCdEf567890',
                attempt_count: 2,
            },
        },
        {
            id: 'evt_06j9k2m3n4p5q6r7s8t9u0v6',
            provider_id: 'pvdr_002',
            provider: 'github',
            event_id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
            event_type: 'pull_request',
            received_at: '2026-03-25T14:11:02Z',
            created_at: '2026-03-25T14:11:02Z',
            delivery_status: DeliveryStatusTypes.Delivered,
            response_code: 200,
            retry_count: 0,
            next_retry_at: null,
            forwarded_to: 'https://api.myapp.com/webhooks/github',
            last_error: null,
            headers: {
                'x-github-event': 'pull_request',
                'x-hub-signature-256': 'sha256=mno345...',
                'content-type': 'application/json',
            },
            payload: {
                action: 'opened',
                number: 42,
                pull_request: {
                    title: 'feat: add SSE event stream',
                    state: 'open',
                    user: { login: 'jdoe' },
                    base: { ref: 'main' },
                    head: { ref: 'feat/sse-stream' },
                },
            },
        },
        {
            id: 'evt_07j9k2m3n4p5q6r7s8t9u0v7',
            provider_id: 'pvdr_001',
            provider: 'stripe',
            event_id: 'evt_3OwVwX2eZvKYlo2C0StuVwXy',
            event_type: 'charge.refunded',
            received_at: '2026-03-25T13:58:22Z',
            created_at: '2026-03-25T13:58:22Z',
            delivery_status: DeliveryStatusTypes.Delivered,
            response_code: 200,
            retry_count: 0,
            next_retry_at: null,
            forwarded_to: 'https://api.myapp.com/webhooks/stripe',
            last_error: null,
            headers: {
                'stripe-signature': 't=1711377502,v1=pqr678...',
                'content-type': 'application/json',
            },
            payload: {
                id: 'ch_3OwVwX2eZvKYlo2C0StuVwXy',
                object: 'charge',
                amount: 2500,
                amount_refunded: 2500,
                currency: 'usd',
                refunded: true,
            },
        },
    ] as WebHookEvent[]
).sort((a, b) => new Date(b.received_at).getTime() - new Date(a.received_at).getTime());

export const MOCK_PROVIDERS: Provider[] = [
    {
        id: 'pvdr_001',
        name: 'Stripe',
        signing_secret: 'whsec_abc123xyz456',
        destination_url: 'https://api.myapp.com/webhooks/stripe',
        is_configured: false,
        created_at: '2026-03-25T13:58:22Z',
    },
    {
        id: 'pvdr_002',
        name: 'Github',
        signing_secret: 'ghsec_def789uvw012',
        destination_url: 'https://api.myapp.com/webhooks/github',
        is_configured: false,
        created_at: '2026-03-25T13:58:22Z',
    },
    {
        id: 'pvdr_003',
        name: 'SNS',
        signing_secret: 'snssec_ghi345rst678',
        destination_url: 'https://api.myapp.com/webhooks/sns',
        is_configured: false,
        created_at: '2026-03-25T13:58:22Z',
    },
];
